import { MapPinned, PackageCheck, Truck, XCircle } from "lucide-react";
import { useParams, useSearchParams } from "react-router-dom";
import { HandoverChildPageHeader } from "../../components/handover/HandoverChildPageHeader";
import { getHandoverCaseFixture } from "../../services/mock/handoverService";
import { auctions } from "../../services/mock/auctionService";
import { NotFoundPage } from "../NotFoundPage";
import "../../styles/delivery-tracking.css";
type DeliveryScenario = "created" | "pickup-pending" | "picked-up" | "in-transit" | "attempted" | "provider-delivered" | "failed" | "retry-created" | "error";
const scenarios: DeliveryScenario[] = ["created", "pickup-pending", "picked-up", "in-transit", "attempted", "provider-delivered", "failed", "retry-created", "error"];
export function DeliveryTrackingPage() { const { caseId } = useParams(); const [params, setParams] = useSearchParams(); const fixture = caseId ? getHandoverCaseFixture(caseId) : undefined; const auction = fixture && auctions.find((item) => item.id === fixture.auctionId); if (!fixture || !auction) return <NotFoundPage />; const requested = params.get("scenario"); const scenario: DeliveryScenario = scenarios.includes(requested as DeliveryScenario) ? requested as DeliveryScenario : "in-transit"; const setScenario = (value: DeliveryScenario) => setParams((current) => { const next = new URLSearchParams(current); next.set("scenario", value); return next; }); const delivered = scenario === "provider-delivered"; const failed = scenario === "failed"; return <main className="container handover-child-page"><HandoverChildPageHeader caseId={fixture.caseId} title="Theo dõi vận chuyển" assetName={auction.assetName} caseReference={fixture.caseReference}/><div className="handover-child-layout"><div><section className="delivery-attempt-card"><Truck aria-hidden="true"/><h2>DeliveryAttempt #{scenario === "retry-created" ? "2" : "1"}</h2><p>Delivery Provider Mock · DLV-••••-5711R</p><strong>{delivered ? "Nhà cung cấp báo đã giao" : failed ? "Lần giao trước chưa thành công" : scenario === "in-transit" ? "Đang vận chuyển" : "Đang chuẩn bị vận chuyển"}</strong><p>ETA: 11:00, 22/07/2026 (GMT+7)</p></section>{failed && <section className="delivery-failure"><XCircle aria-hidden="true"/><p>Attempt 1 không thành công do không thể hoàn tất đối chiếu thời điểm giao. Attempt này được giữ trong lịch sử.</p></section>}<section className="delivery-timeline"><h2>Timeline nhà cung cấp</h2><ol>{[["Đã tạo DeliveryAttempt", "20/07/2026"], ["Đã nhận tài sản để vận chuyển", "21/07/2026"], [delivered ? "Nhà cung cấp báo đã giao" : "Đang vận chuyển", "22/07/2026"]].map(([title, date], index) => <li key={title}><span>{index < 2 || delivered ? <PackageCheck aria-hidden="true"/> : index + 1}</span><div><strong>{title}</strong><small>{date} · Delivery Provider Mock</small></div></li>)}</ol></section>{delivered && <p className="delivery-guardrail"><MapPinned aria-hidden="true"/> Provider báo đã giao chưa đồng nghĩa Customer đã xác nhận nhận tài sản hoặc hồ sơ đã hoàn tất.</p>}</div><aside><section className="delivery-reference"><h2>Thông tin chỉ đọc</h2><p>Provider: Delivery Provider Mock</p><p>Attempt hiện tại không thể được Customer chỉnh sửa.</p><a className="button secondary" href={`/me/handover/${fixture.caseId}/evidence`}>{delivered ? "Xem bằng chứng" : "Quay lại hồ sơ"}</a></section></aside></div>{params.get("demo") === "1" && <label className="handover-demo-toolbar">Điều khiển mô phỏng<select value={scenario} onChange={(event) => setScenario(event.target.value as DeliveryScenario)}>{scenarios.map((item) => <option key={item}>{item}</option>)}</select></label>}</main>; }
