import { AlertTriangle, FileUp, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { HandoverChildPageHeader } from "../../components/handover/HandoverChildPageHeader";
import { getHandoverCaseFixture } from "../../services/mock/handoverService";
import { auctions } from "../../services/mock/auctionService";
import { NotFoundPage } from "../NotFoundPage";
import "../../styles/handover-evidence.css";
type EvidenceScenario = "no-evidence" | "uploading-mock" | "pending-review" | "incomplete" | "accepted" | "issue-open" | "resolved" | "error"; const scenarios: EvidenceScenario[] = ["no-evidence", "uploading-mock", "pending-review", "incomplete", "accepted", "issue-open", "resolved", "error"];
export function HandoverEvidencePage() { const { caseId } = useParams(); const [params, setParams] = useSearchParams(); const [fileName, setFileName] = useState(""); const [issue, setIssue] = useState(false); const fixture = caseId ? getHandoverCaseFixture(caseId) : undefined; const auction = fixture && auctions.find((item) => item.id === fixture.auctionId); if (!fixture || !auction) return <NotFoundPage />; const requested = params.get("scenario"); const scenario: EvidenceScenario = scenarios.includes(requested as EvidenceScenario) ? requested as EvidenceScenario : "no-evidence"; const setScenario = (value: EvidenceScenario) => setParams((current) => { const next = new URLSearchParams(current); next.set("scenario", value); return next; }); const accepted = scenario === "accepted" || scenario === "resolved"; return <main className="container handover-child-page"><HandoverChildPageHeader caseId={fixture.caseId} title="Bằng chứng và vấn đề" assetName={auction.assetName} caseReference={fixture.caseReference}/><div className="handover-child-layout"><div><section className="evidence-upload"><FileUp aria-hidden="true"/><h2>Bằng chứng mô phỏng</h2><p>Chỉ tạo local preview, không tải tệp lên mạng.</p><label className="evidence-file-input">Chọn tệp<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 5_000_000) { setFileName("Tệp vượt quá 5 MB"); return; } setFileName(file.name); setScenario("pending-review"); }}/></label>{fileName && <p className="evidence-preview">Preview cục bộ: {fileName}</p>}</section><section className="evidence-list"><h2>Trạng thái bằng chứng</h2><p>{accepted ? "3/3 mục đã được chấp nhận." : "1/3 mục được ghi nhận; receipt đang bị chặn."}</p><strong>{accepted ? "Bằng chứng đã đủ" : "Đang chờ bổ sung hoặc xem xét"}</strong></section><button className="button secondary" onClick={() => setIssue(true)}>Báo cáo vấn đề</button>{issue && <section className="evidence-issue"><AlertTriangle aria-hidden="true"/><h2>Vấn đề đang mở</h2><p>Thông tin mô phỏng được ghi nhận để xem xét; Customer không thể tự giải quyết blocker.</p><button className="button secondary" onClick={() => setIssue(false)}>Đóng</button></section>}</div><aside><section className="evidence-guard"><ShieldCheck aria-hidden="true"/><h2>Điều kiện Receipt</h2><p>{accepted ? "Bằng chứng đã được chấp nhận." : "Bằng chứng chưa đủ hoặc chưa được chấp nhận nên chưa thể xác nhận đã nhận."}</p></section></aside></div>{params.get("demo") === "1" && <label className="handover-demo-toolbar">Điều khiển mô phỏng<select value={scenario} onChange={(event) => setScenario(event.target.value as EvidenceScenario)}>{scenarios.map((item) => <option key={item}>{item}</option>)}</select></label>}</main>; }
